language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -U install --settings .m2/travis-settings.xml'
env:
  global:
  - secure: QypInPX/tWRHlUTwKwnC2CXVXZ+cqNWMxhw7622CKg4sKaJj7aTtaNtIMRp29ESGuQEyAQot9Yf1iZBDCoG9D8iz1FAnoMgKtL/ie1ZHr9P/D5HWgOhjgNgpVnZrnyRXI97aMEmdD9EMjMIdjQN2jYR9g4wAV/IGxDhHm9+xQt1rpgOl0NPffuYJMcqfMgixm1CKygWRHs7adH/yR9favoNINLwYOSj9IxOAAgmHjbHE1EO4+cRk4TitvsEJwH4jNmp58KcmEhr3oodUidxk6BYhwjV+mkttk4KrGS+wP7QSG7Bp1DxPAMjk7uiIrhOuSintZlBzAaKKCCLGaoANxAGpeEK63j3lcVYw/MHYW0voIFr2QP3tqMnUB1PbF3j9IzoIzSJLudq+9uPq2V6MbzqWSU9oIWMRQu8fdUlCLP86GH9MBlXuTbfH3hskVqoUSWCm54sVJI0PqPV3jc8apf+U6zmo2f7S4dg96M/p5IRex9LxmyC5v+GIHu7rKWEPMswB6I5zeQRCedcUyXt6yoGg2KwB58Nn4GKJpdpUpgnqfFkWEdxBgGD7pbaadtMLi9K08s1WKShGJgCk/2ksf7ykQq85i6WUjrvjnOz/9dFAlYyx5I7QewsuOFXYnYSbDHG6zy1laEG0+wW1eT9BJTN0F3bhkU2I/todhpMd5ko=
  - secure: puFq1PvXAQ4Yw3MASIiF33svgck1Ujgy65c4H8LCNsdnY1HT858naaYj9Eh5ZUiiINQFw5a9KBMGaoJezidEMiO6KlU3mWtJmQdPetrUhaEkUqlM6vpemCHiTnP/fGSjcj9X+51jwyQx4TD7MA4VYMdDjLSF/sYRc4JrxC6bA7WzhJDiIFDryb/V3yRP/xrFBUgizlBPzqN0vv5mwUrMhfuVZRfd1W95UD5qzTH2pguopmVUq9P/X1OH5j6NRgUB8vHZlN6KwD0dLyuh0D4cF4sUY7GsEPNL1GF7peww4bC/bicNVsAgJmbLxgQdTMRfX5pCeJ5ur1ZU563xMXX3t3ctlW8gIoW6Xw+E8r7/HPFrmN3rTeEUNbAv2y2Rq0yF8tVNt0janyo9M++Bjlqk4SGvqL4Mq7AMfNkP5yHt0jMEIo4c1jExhCF5F8UWAErIA1C4Apqp/tJEf9oGeBhqZvh3foYYLGOlQEHZc6Wc5n3j8tq/VbgA1gMbWHVvxYAx5xcNTl4R4+BgWE1iI/Yc9IJ6L3PoL5iV5pj/RYgLGLtZe7BJUYsgPnRm3Y4UgIPlaIctKSYZqSZrvZMpS48YEPMV+T/rhN4Da3y2XIHK2T7XklB6iP8G1IDBvqhNZU9bweS3PhKSsDtrygPw9HEEOjeVsxJFo4zJqhL2iltUcNM=
